### PR TITLE
Updated to Neo4j 2.0

### PR DESCRIPTION
**Pull request by craigtaverner**
I updated to Neo4j 2.0 with a few tiny changes:
- Changed version in pom.xml
- Added source/target specifications to compiler in pom.xml (to allow for annotations, because I was getting errors on my Java 1.7.0_51 (sun/oracle))
- Changed ServerBuilder to CommunityServerBuilder, since the former has been renamed in Neo4j 2.0

Then did some small cleanup:
- Fixed README path (was missing 'service' component from @Path("/service"))
- Deleted target binaries from git (probably was added in original commit by mistake)
- Changed tests to run on port 7575 to not clash with running server (saving me time)

### CODE REVIEW

**Comment by freshteapot** [comment]
Good job Craig. I just forked this project to update the readme to include "/service". But you beat me to it :)

**Comment by craigtaverner** [comment]
Thanks. Pity the maintained has not responded to the pull request. I noticed that Neo4j 2.0 users are building server extensions from scratch. It seems easy enough, but I especially liked the testing framework in this template, because it did stuff I did not know how to do off the top of my head, so I'm happy to continue using it myself.

**Comment by dmontag** [comment]
Hey Craig & Chris, so sorry. Was totally not expecting contributions to this! Really appreciate the work you've put into it. I will try and spend some time to sort out your contributions vs the changes I've made. 

If you're considering contributing more, I'd appreciate a heads-up so I don't miss it / end up doing redundant changes.

**Comment by craigtaverner** [comment]
I thought github notified you when I did this work last month. But I know how it is, with far too many mails coming in so they get filtered away. In any case, it was not planned work. Next time I'll send a separate email, either before I send the pull request, or after if it was impromptu work like this.

**Pull request closed without merging**
